# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ceb623cb22cbff69c44666dd9030a03cb40381a30f867d3fb8218dbe275b7ead95dd3b4f4207465f32cf5ad376be01847bfa9a90a5f2d39fa5359e5f848df94b

test:
  secret_key_base: f09fa875efd5106477f6627d95ea786d8bf87b1a9a6191614d846537672e9e724af54477392555d59dbd987e973ebb2e4e0c83339f06ecafe36a51b57c2cd78d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
